### ISSUE TITLE
BlogのCRUD機能（Scaffold使用すること）

### ISSUE THREAD

**Issue by Kazoo0330** [ks1590/day10_work#1]
- [x] **issue#issue番号でブランチを作成し、そのブランチで下記の開発をすること。**
(ブランチ例)
**`issue#1`**

- [x] `$ bundle install`
- [x] `$ rails db:create`
- [x] `$ rails g scaffold Blog title:string content:text`
- [x] `$ rails db:migrate`
- [x] `$ rails s`（動作確認）

- [x] 上記ができたらgithubにpushすること。

**Comment by Kazoo0330** [comment]
@saecocco 
矢野さんお願いいたします！

**Comment by saecocco** [comment]
@ks1590 　鈴木リーダー
issue#1をpushしたのでご確認お願い致します。
（皆さんのPCで作動するかわかりませんが、一旦gemfile書き換えた状態のものです。）
矢野
